packages:
  - "."

allowBuilds:
  "@tailwindcss/oxide": true
  workerd: true
  sharp: true
  esbuild: true
  "@prisma/client": true
  better-sqlite3: true
  "@prisma/engines": true
  prisma: true

overrides:
  better-auth: "~1.6.15"
  better-call: "^1.3.5"
